---
abstract: 'Dancer wrapper for Business::PayPal::API::ExpressCheckout'
author:
  - 'Lyn St George <lyn@zolotek.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-PaypalExpressRoutes
no_index:
  directory:
    - t
    - inc
requires:
  Business::PayPal::API::ExpressCheckout: 0.14
  Dancer: 1.3098
  Dancer::Plugin::Database: 2.08
version: 0.12
